name: Publish extension

on:
  release:
    types: [published]

jobs:
  publish_release_artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: kogito-tooling

      # This bash script returns the `tag` name for the release. Will match "/refs/[tags/heads]/[tag]"
      - name: Parse `tag`
        id: release-tag
        run: |
          echo ::set-output name=tag::$(node -e "console.log('${{ github.ref }}'.match(/^.*\/(.+)$/)[1])")

      # This bash script returns 0 if equal and 1 otherwise. Will fail if versions are not equal.
      - name: Check release `tag` against `lerna.json.version`
        run: |
          echo "$(node -e "console.log(require('./kogito-tooling/lerna.json').version);")"
          [ "${{ steps.release-tag.outputs.tag }}" == "$(node -e "console.log(require('./kogito-tooling/lerna.json').version);")" ]

      - name: Update Extension
        id: update_extension
        run: |
          curl -sSLo chrome_extension.zip https://github.com/kiegroup/kogito-tooling/releases/download/${{ steps.release-tag.outputs.tag }}/chrome_extension_kogito_kie_editors_${{ steps.release-tag.outputs.tag }}.zip
          access_token::=$(curl -X POST -fsS "https://oauth2.googleapis.com/token" -d "client_id=${{ secrets.CLIENT_ID }}&client_secret=${{ secrets.CLIENT_SECRET }}&refresh_token=${{ secrets.REFRESH_TOKEN }}&grant_type=refresh_token"
          uploadResponse=$(curl -X PUT -sS "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${{ secrets.EXTENSION_ID }}" -H "Authorization:Bearer ${access_token}" -H "x-goog-api-version:2}" -T ./chrome_extension.zip )
          echo "$uploadResponse"
          echo ::set-output name=upload_status::$(echo "$uploadResponse" | jq -r '.uploadState')

      - name: Check Upload
        run: |
          [ "${{ steps.update_extension.outputs.upload_status }}" == 'SUCCESS' ]

      - name: Publish Extension
        id: publish_extension
        run: |
          access_token::=$(curl -X POST -fsS "https://oauth2.googleapis.com/token" -d "client_id=${{ secrets.CLIENT_ID }}&client_secret=${{ secrets.CLIENT_SECRET }}&refresh_token=${{ secrets.REFRESH_TOKEN }}&grant_type=refresh_token"
          publishResponse=$(curl -X POST -sS "https://www.googleapis.com/chromewebstore/v1.1/items/${{ secrets.EXTENSION_ID }}/publish" -H "Authorization:Bearer ${access_token}" -H "x-goog-api-version:2" -H "Content-Length:0" -H "publishTarget:trustedTesters")
          echo "$publishResponse"
          echo ::set-output name=publish_status::$(echo "$publishResponse" | jq -r '.status | .[0]')

      - name: Check Publish
        run: |
          [ "${{ steps.update_extension.outputs.publish_status }}" == 'OK' ]
